### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by WARDOGSK93** [WARDOGSK93/CoD-BO-Gamemode#1]
- [ ] Add Gamemode: **GunGame**
- [ ] Add Gamemode: **Team GunGame**
- [ ] Add Gamemode: **SharpShooter**
- [ ] Add Gamemode: **Sticks & Stones**
- [ ] Add Gamemode: **LockSmith**
- [ ] Add Gamemode: **Locked Out**
- [ ] Add Gamemode: **One in the Chamber**
