### ISSUE TITLE
TODO List (Black Ops III)

### ISSUE THREAD

**Issue by WARDOGSK93** [WARDOGSK93/CoD-BO-Gamemode#2]
- [x] Add Gamemode: **GunGame**
- [ ] Add Gamemode: **Team GunGame** - _Needs coop testing_
- [x] Add Gamemode: **SharpShooter**
- [ ] Add Gamemode: **LockSmith**
- [ ] Add Gamemode: **Locked Out**
- [x] Add Gamemode: **Sticks & Stones**
- [x] Add Gamemode: **One in the Chamber**

_See **UGX-Mods.com** thread deatils on each gamemode_

- [x] Add Gamemode Completion System

- [ ] Port to Call of Duty: Black Ops 3

_Please comment any suggestions you might have either on the **UGX-Mods.com** thread_
